dist: trusty
sudo: required

env:
  - VERSION=$TRAVIS_COMMIT

before_script:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - make pull
  - make build 

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    make tag push;
    fi
