consumes:
  - application/json
info:
  title: Kubernikus
  version: 1.0.0
produces:
  - application/json
swagger: '2.0'
securityDefinitions:
  keystone:
    description: OpenStack Keystone Authentication
    type: apiKey
    in: header
    name: x-auth-token

security: []
  
paths:
  /api/:
    get:
      operationId: ListAPIVersions
      summary: List available api versions
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ApiVersions'
        401:
          description: Unauthorized
  /api/v1/clusters/:
    get:
      operationId: ListClusters
      summary: List available clusters
      responses:
        200:
          description: OK 
          schema:
            type: array
            items:
              $ref: '#/definitions/Cluster'
      security:
        - keystone: []
    post:
      operationId: CreateCluster
      summary: Create a cluster
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Cluster'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Cluster'
      security:
        - keystone: []

  /api/v1/clusters/{name}:
    get:
      operationId: ShowCluster
      summary: Show the specified cluser
      responses:
        200: 
          description: OK
          schema:
            $ref: '#/definitions/Cluster'
      security:
        - keystone: []
    parameters:
      - uniqueItems: true
        type: string
        name: name
        required: true
        in: path

definitions:
  ApiVersions:
    required:
      - versions
    properties:
      versions:
        description: versions are the api versions that are available.
        type: array
        items:
          type: string
  Cluster:
    type: object
    properties:
      name:
        description: name of the cluster
        type: string
  Principal:
    type: object
    properties:
        name:
          description: username
          type: string
        id:
          description: userid
          type: string
        account:
          description: account id
          type: string
        roles:
          description: list of roles the user has in the given scope 
          type: array 
          items:
            type: string

