{{/* vim: set filetype=gotexttmpl: */ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 2379
  selector:
    app: {{ include "fullname" . }}
