apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: kubernikus-groundctl
  labels:
    app: kubernikus
    type: groundctl

spec:
  template:
    metadata:
      labels:
        app: kubernikus
        type: groundctl
    spec:
      containers:
        - name: api
          image: {{ .Values.global.image | quote }}
          args:
            - --auth-url={{ .Values.groundctl.auth_url | quote }}
            - --auth-username={{ .Values.groundctl.auth_username | quote }}
            - --auth-password={{ .Values.groundctl.auth_password | quote }}
            - --auth-domain={{ .Values.groundctl.auth_domain | quote }}
            - --auth-project={{ .Values.groundctl.auth_project | quote }}
            - --auth-project-domain={{ .Values.groundctl.auth_project_domain | quote }}
            - --v={{ default 1 .Values.groundctl.log_level }}
