apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: kubernikus-groundctl
  labels:
    app: kubernikus
    type: groundctl

spec:
  template:
    metadata:
      labels:
        app: kubernikus
        type: groundctl
    spec:
      containers:
        - name: groundctl
          image: {{ .Values.global.image | quote }}
          args:
            - groundctl
            - --auth-url={{ .Values.openstack.auth_url | quote }}
            - --auth-username={{ .Values.openstack.auth_user_id | quote }}
            - --auth-password={{ .Values.openstack.auth_user_password | quote }}
            - --auth-domain={{ .Values.openstack.auth_domain | quote }}
            - --auth-project={{ .Values.openstack.auth_project | quote }}
            - --auth-project-domain={{ .Values.openstack.auth_project_domain | quote }}
            - --v={{ default 1 .Values.groundctl.log_level }}
