apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: kubernikus-api
  annotations:
    vice-president: "true"
    
spec:
  tls:
     - secretName: kubernikus-api
       hosts: [{{.Values.kubernikus.domain}}]
  rules:
    - host: {{.Values.kubernikus.domain}}
      http:
        paths:
        - path: /
          backend:
            serviceName: kubernikus-api
            servicePort: {{ .Values.api.port }}
