apiVersion: v1
kind: Service
metadata:
  name: k8sniff-ingress-lb
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    role: k8sniff-ingress-lb
  externalIPs:
    - {{ .Values.k8sniff.external_service_ip }}
