image: sapcc/kubernikus
imageTag: latest

openstack:
  auth_url: "http://identityv3.openstack:5000/v3"
  auth_url: "http://identityv3.openstack:5000/v3"
  auth_username: "openstack"
  auth_password: "secret!"
  auth_domain: "Default"
  auth_project: "master"
  auth_project_domain: "Default"

kubernikus:
  domain: "kubernikus.replaceme.cloud.sap"

api:
  port: 1234
  log_level: 1

groundctl:
  log_level: 1

revisionHistoryLimit: 3

k8sniff:
  tag: "8d5bf771eb906c58acfdd68e553f9408432043fa"
  metrics_port: 9091
  external_service_ip: ""
