# Default values for kube-master.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: quay.io/coreos/hyperkube
  tag: v1.6.1_coreos.0
  pullPolicy: IfNotPresent

openstack:
  authUrl:
  username:
  password:
  domainName:
  projectName:
  region:
  lbSubnetID:
  routerID:

# specify a different certsSecretName if you want to use
# an exiting secret
certsSecretName: secrets
# Use these keys to specify the certs as helm values
#certs:
#  kube-clients-ca.pem:
#  etcd-clients-ca.pem:
#  etcd-clients-apiserver.pem:
#  etcd-clients-apiserver.key:
#  kube-clients-ca.pem:
#  kube-clients-ca.key:
#  kube-controller-manager.pem:
#  kube-controller-manager.key:
#  kube-scheduler.pem:
#  kube-scheudler.key:
#  kube-nodes-ca.pem:
#  kube-nodes-ca.key:
#  kube-nodes-apiserver.pem:
#  kube-nodes-apiserver.key:
#  tls-ca.pem:
#  tls-kube-apiserver.pem:
#  tls-kube-apiserver.key:
#  tls-sni.pem:
#  tls-sni.key:

api:
  replicaCount: 1
  # ingressHost:
  flags:
    secure-port: 6443
    admission-control: NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
    advertise-address: 10.3.0.1
    allow-privileged: true
    authorization-mode: RBAC
    cloud-config: /etc/kubernetes/cloudprovider/openstack.config
    cloud-provider: openstack
    etcd-servers: http://etcd:2379
    experimental-bootstrap-token-auth: true
    runtime-config: rbac.authorization.k8s.io/v1alpha1,extensions/v1beta1=true,extensions/v1beta1/thirdpartyresources=true
    service-cluster-ip-range: 10.180.1.0/24
    #Cert Spraz
    client-ca-file: /etc/kubernetes/certs/kube-clients-ca.pem
    etcd-cafile: /etc/kubernetes/certs/etcd-clients-ca.pem
    etcd-certfile: /etc/kubernetes/certs/etcd-clients-apiserver.pem
    etcd-keyfile: /etc/kubernetes/certs/etcd-clients-apiserver.key
    kubelet-certificate-authority: /etc/kubernetes/certs/kube-nodes-ca.pem
    kubelet-client-certificate: /etc/kubernetes/certs/kube-nodes-apiserver.pem
    kubelet-client-key: /etc/kubernetes/certs/kube-nodes-apiserver.key
    tls-ca-file: /etc/kubernetes/certs/tls-ca.pem
    tls-cert-file: /etc/kubernetes/certs/tls-kube-apiserver.pem
    tls-private-key-file: /etc/kubernetes/certs/tls-kube-apiserver.key
    tls-sni-cert-key: /etc/kubernetes/certs/tls-sni.pem,/etc/kubernetes/certs/tls-sni.key
    # experimental-keystone-ca-file:
    # experimental-keystone-url;

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

controllerManager:
  replicaCount: 1
  flags:
    allocate-node-cidrs: true
    cloud-config: /etc/kubernetes/cloudprovider/openstack.config
    cloud-provider: openstack
    cluster-cidr: 10.180.128.0/17
    cluster-name: kubernetes
    cluster-signing-cert-file: /etc/kubernetes/certs/kube-nodes-ca.pem
    cluster-signing-key-file: /etc/kubernetes/certs/kube-nodes-ca.key
    configure-cloud-routes: true
    kubeconfig: /etc/kubernetes/config/kubeconfig
    root-ca-file: /etc/kubernetes/certs/kube-clients-ca.pem
    service-account-private-key-file: /etc/kubernetes/certs/kube-clients-ca.key
    service-cluster-ip-range: 10.180.1.0/24
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

scheduler:
  replicaCount: 1
  flags:
    kubeconfig: /etc/kubernetes/config/kubeconfig
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

revisionHistoryLimit: 3
