resources:
  - name: kubernikus.git
    type: git
    source:
      username: sapcc-bot
      password: ((github-com-access-token))
      uri:    https://github.com/sapcc/kubernikus.git
      branch: ci

#  - name: secrets.git
#    type: git
#    source:
#      uri:         git@github.wdf.sap.corp:cc/secrets.git
#      private_key: ((secrets-ssh-key))
#      branch:      master

  - name: kubernikus.version
    type: time-version-resource
    source:
      prefix: v
      property_name: VERSION

  - name: kubernikus.image
    type: docker-image
    source:
      repository: sapcc/kubernikus
      username:   ((docker-hub-username))
      password:   ((docker-hub-password))

resource_types:
  - name: time-version-resource
    type: docker-image
    source:
      repository: hub.global.cloud.sap/d062392/time-version-resource

jobs:
  - name: build
    serial: true
    plan:
      - aggregate:
        - get: kubernikus.git
          trigger: true
        - get: kubernikus.version

      - put: kubernikus.image
        params:
          build: kubernikus.git/
          tag: kubernikus.version/version
          build_args_file: kubernikus.version/properties.json
          tag_as_latest: true
          build_args:
            http_proxy: http://proxy.wdf.sap.corp:8080
            https_proxy: http://proxy.wdf.sap.corp:8080
            no_proxy: sap.corp,cloud.sap,127.0.0.1,localhost

#  - name: staging
#    serial: true
#    plan:
#      - aggregate:
#        - get: kubernikus.git
#          trigger: true
#          passed: [build]
#        - get: secrets.git
#
#      - task: deploy
#        file: secrets.git/ci/kubernikus/task-helm-upgrade.yaml
#        params:
#          REGION: staging
#          GITHUB_TOKEN: ((github-access-token))

  # Add new regions above this line, but note that you need to do a
  # manual `helm install` first. This pipeline can only `helm upgrade`.
  # When the pipeline is up and running, set the image tag to
  # `DEFINED_BY_PIPELINE` so that a manual `helm upgrade` fails cleanly
  # and points the user to the pipeline.
