post_failure_to_slack: &post_failure_to_slack
  put: slack-alert
  params:
    channel: '#kubernikus'
    username: 'Concourse'
    icon_emoji: ':airplane:'
    silent: 'true'
    text: |
      :boom: <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_PIPELINE_NAME $BUILD_JOB_NAME job #$BUILD_NAME failed>

resources:
  - name: kubernikus.git
    type: git
    source:
      username: sapcc-bot
      password: ((github-com-access-token))
      uri:    https://github.com/sapcc/kubernikus.git
      branch: master

  - name: secrets.git
    type: git
    source:
      uri:         git@github.wdf.sap.corp:cc/secrets.git
      private_key: ((secrets-ssh-key))
      branch:      master

  - name: kubernikus.image
    type: docker-image
    source:
      repository: sapcc/kubernikus
      username:   ((docker-hub-username))
      password:   ((docker-hub-password))

  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack-webhook-url}}

resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

jobs:
  - name: staging
    serial: true
    plan:
      - aggregate:
        - get: kubernikus.git
        - get: secrets.git
        - get: kubernikus.image
          trigger: true
      - task: deploy
        file: kubernikus.git/ci/task-helm-upgrade-kubernikus-admin.yaml
        params:
          KUBERNIKUS_NAME: kubernikus-staging # should be k-staging if you copy this for other regions
          GITHUB_TOKEN: ((github-access-token))
    on_failure:
      <<: *post_failure_to_slack
