{{/* vim: set filetype=gotexttmpl: */ -}}
apiVersion: "extensions/v1beta1"
kind: Deployment
metadata:
  name: {{ include "master.fullname" . }}-apiserver
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.api.replicaCount }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ if eq (toString .Values.api.replicaCount) "1" }}0{{else}}1{{end}}
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ include "master.fullname" . }}-apiserver
  template:
    metadata:
      labels:
        app: {{ include "master.fullname" . }}-apiserver
        release: {{ .Release.Name }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: certs
          secret:
            secretName: {{ .Values.certsSecretName | default (include "master.fullname" .) }}
            items:
{{- include "certItemsFromFlags" .Values.api.flags |indent 14 }}
        - name: cloudprovider
          secret:
            secretName: {{ include "master.fullname" . }}
            items:
              - key: openstack.config
                path: openstack.config
      containers:
        - name: apiserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - /hyperkube
            - apiserver
            - --etcd-servers=http://{{ include "etcd.fullname" . }}:2379
{{- range $key, $value := .Values.api.flags }}
            - --{{ $key }}={{ $value -}}
{{ end }}
          volumeMounts:
            - mountPath: /etc/kubernetes/certs
              name: certs
              readOnly: true
            - mountPath: /etc/kubernetes/cloudprovider
              name: cloudprovider
              readOnly: true
          resources:
{{ toYaml .Values.api.resources | indent 12 }}
