{{/* vim: set filetype=gotexttmpl: */ -}}
apiVersion: "extensions/v1beta1"
kind: Deployment
metadata:
  name: controller-manager
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas:  {{ .Values.api.replicaCount }}
  template:
    metadata:
      labels:
        app: controller-manager
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: certs
          secret:
            secretName: {{ .Values.certsSecretName }}
            items:
              - key: tls-ca.pem
                path: tls-ca.pem
              - key: kube-controller-manager.pem
                path: kube-client.pem
              - key: kube-controller-manager.key
                path: kube-client.key
{{- include "certItemsFromFlags" .Values.controllerManager.flags |indent 14 }}
        - name: config
          configMap:
            name: config
        - name: cloudprovider
          secret:
            secretName: secrets
            items:
              - key: openstack.config
                path: openstack.config
        - name: openstack-hacks
          configMap:
            name: openstack-hacks
      containers:
        - name: controller-manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - /hyperkube
            - controller-manager
{{- range $key, $value := .Values.controllerManager.flags }}
            - --{{ $key }}={{ $value -}}
{{ end }}
          volumeMounts:
            - mountPath: /etc/kubernetes/certs/
              name: certs
              readOnly: true
            - mountPath: /etc/kubernetes/config
              name: config
              readOnly: true
            - mountPath: /etc/kubernetes/cloudprovider
              name: cloudprovider
              readOnly: true
            - mountPath: /var/lib/cloud/data/
              name: openstack-hacks
              readOnly: true
          resources:
{{ toYaml .Values.controllerManager.resources | indent 12 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openstack-hacks
data:
  instance-id: gurkenwurst
