{{/* vim: set filetype=gotexttmpl: */ -}}
{{- if .Values.api.ingressHost }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "master.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: k8sniff
    ingress.kubernetes.io/ssl-passthrough: "true"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}

spec:
  rules:
    - host: {{ .Values.api.ingressHost }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ include "master.fullname" . }}
            servicePort: 6443
    - host: {{ .Values.api.wormholeHost }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ include "master.fullname" . }}
            servicePort: 6553
{{- end }}
