{{/* vim: set filetype=gotexttmpl: */ -}}
apiVersion: "openstack.stable.sap.cc/v1"
kind: "OpenstackSeed"
metadata:
  name: {{ include "master.fullname" . }}-technical-user
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}

spec:
  requires:
  - monsoon3/domain-default-seed
  domains:
  - name: {{ required "missing openstack.domainName" .Values.openstack.domainName }}
    users:
    - name: {{ required "missing openstack.username" .Values.openstack.username }}
      description: "Kubernikus technical user for cluster {{ include "master.fullname" . }}"
      password: {{ required "missing openstack.password" .Values.openstack.password | quote }}
      default_project: {{ required "missing openstack.projectID" .Values.openstack.projectID }}
      roles:
      - project_id: {{ required "missing openstack.projectID" .Values.openstack.projectID }}
        role: member
      - project_id: {{ required "missing openstack.projectID" .Values.openstack.projectID }}
        role: network_admin
