{{/* vim: set filetype=gotexttmpl: */ -}}
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  openstack.config: {{ include (print $.Template.BasePath "/_openstack.config.tpl") .Values.openstack | b64enc}}
{{- range $key, $value := .Values.certs }}
  {{ $key }}: {{ $value | b64enc -}}
{{ end }}
