{{/* vim: set filetype=gotexttmpl: */ -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "master.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
type: Opaque
data:
  openstack.config: {{ include (print $.Template.BasePath "/_openstack.config.tpl") . | b64enc}}

  openstack-auth-url: {{ .Values.openstack.authURL | b64enc }}
  openstack-username: {{ .Values.openstack.username | b64enc }}
  openstack-password: {{ .Values.openstack.password | b64enc }}
  openstack-domain-name: {{ .Values.openstack.domainName | b64enc }}
  openstack-lb-subnet-id: {{ .Values.openstack.lbSubnetID | b64enc }}
  openstack-router-id: {{ .Values.openstack.routerID | b64enc }}
{{- if empty .Values.certsSecretName }}
{{- range list "apiserver-clients-ca-key.pem" "apiserver-clients-ca.pem" "apiserver-clients-system-kube-controller-manager-key.pem" "apiserver-clients-system-kube-controller-manager.pem" "apiserver-clients-system-kube-scheduler-key.pem" "apiserver-clients-system-kube-scheduler.pem" "apiserver-nodes-ca-key.pem" "apiserver-nodes-ca.pem" "etcd-clients-apiserver-key.pem" "etcd-clients-apiserver.pem" "etcd-clients-ca-key.pem" "etcd-clients-ca.pem" "etcd-peers-ca-key.pem" "etcd-peers-ca.pem" "kubelet-clients-apiserver-key.pem" "kubelet-clients-apiserver.pem" "kubelet-clients-ca-key.pem" "kubelet-clients-ca.pem" "tls-ca-key.pem" "tls-ca.pem" "tls-apiserver.pem" "tls-apiserver-key.pem" }}
  {{ . }}: {{ required (printf "missing cert/key: %s" .) (index $.Values.certs .) | b64enc -}}
{{ end }}
{{ end }}
